### ISSUE TITLE
Couldn't load plugin 'Generalizer3' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by onplot** [p0cisk/Generalizer#6]
ImportError: cannot import name 'resources' from 'Generalizer3' (C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\__init__.py) 
Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\__init__.py", line 25, in classFactory
    from .generalizer import generalizer
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\generalizer.py", line 34, in 
    from . import resources
ImportError: cannot import name 'resources' from 'Generalizer3' (C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Generalizer3\__init__.py)

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TomBio
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGeo4W64/apps/qgis/./python
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.
C:\Users\max\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\max\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/max/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\max\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\max\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs

**Comment by yjmenezes** [comment]
Thank you for your work.

I am facing the same error under GNU/Linux  Debian burst and QGIS 3.12.3

ImportError: cannot import name 'resources' from 'Generalizer3' (/home/jmenezes/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Generalizer3/__init__.py)

Versão do Python: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0] 
Versão do QGIS: 3.12.3-București București, 8234261527

**Comment by kikislater** [comment]
This repo is not active anymore ... I updated this plugin to Qgis3, please fill issue here https://github.com/giscan/Generalizer
